### ISSUE TITLE
Some of the dependencies defined in the manifest files have known security vulnerabilities and should be updated

### ISSUE THREAD

**Issue by saranshkataria** [facebook-developer-circle-delhi/Meetups#1]
hapijs / hoek 4.2.0 needs to be upgraded

**Comment by sidvishnoi** [comment]
Which manifest files? Can you help direct first time contributors a bit more?

**Comment by gaurav-gogia** [comment]
So, I looked at this issue some time ago. I couldn't really find "hoek:4.2.0" dependency for a couple of days in the package.json file (the manifest file). Since all the packages that we install are listed there I assumed that hoek would be there too but it wasn't.

I had to go through all the folders and eventually I went through all the files as well. It took a while, maybe it too long. But then, with some help on the internet I was able to find in package-lock.json.

I was wondering why that was. Please shed some light on this? 

Thanks :)

**Comment by saranshkataria** [comment]
@DesmondANIMUS next time refer to the issue id in the pull request to map them together (You can do that by writing # followed by the id)

**Comment by saranshkataria** [comment]
As for the explanation, react-scripts had a reference to hoek, that will not be visible in the package.json since it is not referenced directly. The package-lock.json contains a dependency tree that was generated when you ran npm install, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

**Comment by saranshkataria** [comment]
@DesmondANIMUS the same changes need to be made in folder 13. Could you do those as well?

**Comment by gaurav-gogia** [comment]
Sure, doing it now

**Comment by saranshkataria** [comment]
#4  fixes this. Closing this out. Thanks @DesmondANIMUS
